apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data 
  labels: 
    app: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M 
  storageClassName: do-block-storage
