apiVersion: v1
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data
  labels:
    name: elasticsearch
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: data
    fsType: ext4
    readOnly: true